pipeline {
    agent any
    tools {
        maven 'maven 3.9.8'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
       stage('Deliver') {
    steps {
        sh 'ls -la target'  // Ensure the JAR file is present
        sh 'ls -la jenkins/src'  // Ensure deliver.sh is present
        sh 'chmod +x jenkins/src/deliver.sh'  // Ensure script is executable
        sh 'jenkins/src/deliver.sh'
    }
}
    }
}

        }
    }
}
